title: Youngju Jeon's blog 
description: Hi I'm Youngju Jeon, a learning AI engineer currently interested in Computer Vision. :)
theme: just-the-docs

url: https://lylajeon.github.io

aux_links:
  Template Repository: https://github.com/lylajeon/lylajeon.github.io
